language: node_js
node_js:
    - "5"
before_install:
    - npm install -g jspm
install: true
before_script:
    - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script: npm test
cache:
    directories:
        - jspm_packages

# Travis CI stuff to make 'make' happen
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
