language: node_js
node_js:
    - "5"
before_install:
    - npm install -g jspm
    - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN # Set to avoid the GitHub API limit
install:
    - npm install # Will also run 'jspm install' afterwards (checkout the package.json > scripts > postinstall)
script: npm test # Defined in the package.json (scripts > test)
cache:
    directories:
        - node_modules
        - jspm_packages

# Travis CI stuff to make 'make' happen
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
