language: node_js
node_js:
    - "6.8.1"
    - "6.8.0"
    - "6.7.0"
    - "6.6.0"
before_install:
    - npm install -g yarn jspm
    - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN # Set to avoid the GitHub API limit
    - yarn config set ignore-optional false
install:
    - yarn # Will also run 'jspm install' afterwards (checkout the package.json > scripts > postinstall)
    - jspm install
script: npm test # Defined in the package.json (scripts > test)
cache:
    directories:
        - node_modules
        - jspm_packages
os:
  - osx
  - linux
