language: node_js
node_js:
    - "5"
before_install:
    - npm install -g jspm
cache:
    directories:
        - jspm_packages
        - node_modules
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
